global:
  sendAnonymousUsage: false

api:
  dashboard: true

providers:
  docker:
    network: systemd-foxws
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

log:
  level: INFO
  format: common

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

certificatesResolvers:
  myresolver:
    acme:
      email: email@example.com
      storage: /etc/traefik/acme/acme.json
      tlschallenge: true
