#!/bin/sh

# Build images
podman build \
    -t foxws-nginx \
    --file=build/nginx/Dockerfile \
    --env=../../.env \
    --no-cache

podman build \
    -t foxws-app \
    --file=build/app/Dockerfile \
    --env=../../.env \
    --no-cache
