http:
  services:
    cockpit:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:9090"
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /run/secrets/cert.pem
#         keyFile: /run/secrets/key.pem
