global:
  sendAnonymousUsage: false

log:
  level: WARN
  format: common

api:
  insecure: false
  debug: false
  dashboard: true

providers:
  docker:
    watch: true
    network: systemd-traefik
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

certificatesResolvers:
  myresolver:
    acme:
      email: email@example.com
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: "0"
